### ISSUE TITLE
[Bug] 100% CPU Usage When Idle in sglang

### ISSUE THREAD

**Issue by zyearw1024** [sgl-project/sglang#1730]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

## Issue Description

While running sglang with no active workload, I observed 100% CPU usage without any CUDA utilization. This issue appears to be caused by a non-blocking ZMQ receive operation in the `recv_requests` function of `scheduler.py`.

## Steps to Reproduce

1. Start sglang
2. Run `htop` to observe high CPU usage
3. Use `py-spy` to collect stack information for the high CPU process:
   ```
   3.1. pip3 install py-spy 
   3.2. sudo env "PATH=$PATH" py-spy top -p <PID>
   ```

## Findings

The `py-spy` output shows that most of the time is spent in the `recv_requests` function:

```
Collecting samples from '/usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=21, pipe_handle=23)
Collecting samples from '/usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=21, pipe_handle=23) --multiprocessing-fork' (python v3.10.15)
Total Samples 7732
GIL: 64.00%, Active: 200.00%, Threads: 3

  %Own   %Total  OwnTime  TotalTime  Function (filename)
100.00% 100.00%   77.32s    77.32s   _recv_msg (torch/_inductor/compile_worker/subproc_pool.py)
 51.00%  67.00%   34.42s    49.74s   recv_pyobj (zmq/sugar/socket.py)
  9.00%  16.00%   11.51s    15.32s   __init__ (zmq/error.py)
  7.00%  74.00%    8.93s    58.67s   recv_requests (scheduler.py)
 12.00%  14.00%    5.15s     6.69s   check_memory (scheduler.py)
  3.00%  18.00%    4.28s    12.59s   run_step (scheduler.py)
  7.00%   7.00%    3.81s     3.81s   _handle_fromlist (<frozen importlib._bootstrap>)
  6.00% 100.00%    3.70s    77.32s   event_loop (scheduler.py)
  2.00%   2.00%    1.65s     1.65s   send_results (scheduler.py)
  1.00%   1.00%    1.62s     1.62s   get_new_batch_prefill (scheduler.py)
  2.00%   2.00%   0.910s    0.910s   available_size (memory_pool.py)
  0.00%   0.00%   0.710s    0.710s   process_input_requests (scheduler.py)
  0.00%   0.00%   0.630s    0.630s   evictable_size (radix_cache.py)
  0.00% 100.00%   0.000s    77.32s   _bootstrap_inner (threading.py)
```

The problematic code in `scheduler.py` is:

```python
def recv_requests(self):
    if self.tp_rank == 0:
        recv_reqs = []

        while True:
            try:
                recv_req = self.recv_from_tokenizer.recv_pyobj(zmq.NOBLOCK)
            except zmq.ZMQError:
                break
            recv_reqs.append(recv_req)
    else:
        recv_reqs = None

    if self.tp_size != 1:
        recv_reqs = broadcast_pyobj(recv_reqs, self.tp_rank, self.tp_cpu_group)
    return recv_reqs
```

The issue is likely caused by the use of `zmq.NOBLOCK` in the ZMQ receive operation.

## Proposed Solution

After analyzing the issue, I propose implementing a blocking receive operation with a timeout instead of the current non-blocking approach. This should significantly reduce CPU usage during idle periods while still maintaining system responsiveness.

I will attempt to implement this solution and submit a pull request with the proposed changes for review.

## docker-compose.yml
```yml
version: "3.9"

x-node-common:
  &node-common

  restart: always
  platform: linux/amd64

  environment:
    &node-common-env
    TZ: Asia/Shanghai
    LOG_LEVEL: INFO
  image: lmsysorg/sglang:v0.3.3.post1-cu121-srt
 

  runtime: nvidia

  logging:
    driver: json-file
    options:
      max-size: "100m"
      max-file: "10"

services:

  ant-sglang-20241016-01:
    <<: *node-common
    container_name: ant-sglang-20241016-01
    shm_size: '8gb'
    volumes:
      - /data/models/Qwen2.5-3B-Instruct-AWQ:/data/models/Qwen2.5-3B-Instruct-AWQ
    environment:
      <<: *node-common-env
      CUDA_VISIBLE_DEVICES: 0

    ports:
       - 43567:43567

    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "--location", "http://127.0.0.1:43567/health"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 12
    #   start_period: 3m
 
  

    entrypoint: python3 -m sglang.launch_server --host 0.0.0.0 --port 43567 --model-path /data/models/Qwen2.5-3B-Instruct-AWQ --tp 1 --quantization awq --mem-fraction-static 0.75 --context-length 32768 --served-model-name qwen2.5-3b-awq  

    # entrypoint: python3 -c "import time;time.sleep(100000000)"
```

### Environment

```
root@abd022dbffbe:/sgl-workspace# python3 -m sglang.check_env
Python: 3.10.15 (main, Sep  7 2024, 18:35:33) [GCC 9.4.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3070 Ti
GPU 0 Compute Capability: 8.6
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 555.42.06
PyTorch: 2.4.0+cu121
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.45.2
requests: 2.32.3
tqdm: 4.66.5
```
