### ISSUE TITLE
[Bug] Unable to run Qwen2-VL with OpenAI server

### ISSUE THREAD

**Issue by Quang-elec44** [sgl-project/sglang#1759]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

I cannot find the right way to run Qwen2-VL with OpenAI or with example script ([here](https://github.com/sgl-project/sglang/blob/main/docs/en/sampling_params.md))

### Reproduction

Step 1: Start the server with docker-compose. Model: `Qwen/Qwen2-VL-7B-Instruct-AWQ`

```yaml
services:
  llm-sglang:
    image: lmsysorg/sglang:latest
    container_name: llm-sglang
    restart: unless-stopped
    environment:
      HUGGING_FACE_HUB_TOKEN: ${HF_TOKEN}
    ports:
      - "${PORT}:${PORT}"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ipc: host
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    networks:
      - ai-assistant
    env_file: 
      - .env
    command: >
      python3 -m sglang.launch_server
      --model ${MODEL}
      --host 0.0.0.0
      --port ${PORT}
      --api-key ${API_KEY}
      --served-model-name ${SERVED_MODEL_NAME}
      --tensor-parallel-size ${TP}
      --mem-fraction-static ${MFS}
      --random-seed 42
      --enable-p2p-check
      --show-time-cost
      --context-length ${CONTEXT_LENGTH}

networks:
  ai-assistant:
    external: true
```

Step 2: Run the below script

```
from openai import OpenAI

# Modify OpenAI's API key and API base to use vLLM's API server.
openai_api_key = "sk-no-key-required"
openai_api_base = "http://localhost:8009/v1"

client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)

from PIL import Image
import base64
from io import BytesIO

image = Image.open("images/page_7.png")
buffered = BytesIO()
image.save(buffered, format="PNG")
image_base64 = base64.b64encode(buffered.getvalue()).decode('utf-8')

chat_completion_from_base64 = client.chat.completions.create(
    messages=[{
        "role": "user",
        "content": [
            {
                "type": "text",
                "text": "Extract all texts in the image."
            },
            {
                "type": "image_url",
                "image_url": {
                    "url": f"data:image/jpeg;base64,{image_base64}"
                },
            },
        ],
    }],
    model="gpt-4o",
    temperature=0.0,
    max_tokens=2048,
)

result = chat_completion_from_base64.choices[0].message.content
print(f"Chat completion output: {result}")
>>> Chat completion output: I'm sorry, but as an AI language model, I don't have the ability to access or view images. Please provide me with the text you want me to extract, and I'll be happy to help you with that.
```

The above script is from the `vllm` example, which is similar to the OpenAI guide [here](https://platform.openai.com/docs/guides/vision), and it works fine with the `vllm` server. However, the result seems different and it looks like the server cannot see the image.

Then I run your example script as below:

```
import requests

response = requests.post(
    "http://localhost:8009/generate",
    json={
        "text": "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n"
                "<|im_start|>user\n<image>\nExtract all texts in the image.<|im_end|>\n"
                "<|im_start|>assistant\n",
        "image_data": image_base64,
        "sampling_params": {
            "temperature": 0,
            "max_new_tokens": 1024,
        },
    },
    headers={"Authorization": "Bearer sk-no-key-required"}
)
print(response.json())
```

There was an error and the server crashed completely.

```
llm-sglang  | [2024-10-22 18:32:16 TP0] Traceback (most recent call last):
llm-sglang  |   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1133, in run_scheduler_process
llm-sglang  |     scheduler.event_loop_normal()
llm-sglang  |   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
llm-sglang  |     return func(*args, **kwargs)
llm-sglang  |   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 276, in event_loop_normal
llm-sglang  |     self.process_input_requests(recv_reqs)
llm-sglang  |   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 347, in process_input_requests
llm-sglang  |     self.handle_generate_request(recv_req)
llm-sglang  |   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 387, in handle_generate_request
llm-sglang  |     req.origin_input_ids = self.pad_input_ids_func(
llm-sglang  |   File "/sgl-workspace/sglang/python/sglang/srt/models/qwen2_vl.py", line 521, in pad_input_ids
llm-sglang  |     non_image_tokens = input_ids[: image_indices[image_cnt]]
llm-sglang  | IndexError: list index out of range
llm-sglang  | 
llm-sglang  | /usr/lib/python3.10/multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
llm-sglang  |   warnings.warn('resource_tracker: process died unexpectedly, '
llm-sglang  | Traceback (most recent call last):
llm-sglang  |   File "/usr/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
llm-sglang  |     cache[rtype].remove(name)
llm-sglang  | KeyError: '/mp-ay9jmxzc'
```

### Environment

Python: 3.10.15 (main, Sep  7 2024, 18:35:33) [GCC 9.4.0]
CUDA available: True
GPU 0: NVIDIA A10G
GPU 0 Compute Capability: 8.6
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 550.107.02
PyTorch: 2.4.0+cu121
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.45.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.10
fastapi: 0.115.2
hf_transfer: 0.1.8
huggingface_hub: 0.26.1
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.1.0
pydantic: 2.9.2
uvicorn: 0.32.0
uvloop: 0.21.0
zmq: 26.2.0
vllm: 0.6.3.post1
multipart: 0.0.12
openai: 1.52.0
anthropic: 0.36.2
NVIDIA Topology: 
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0-47    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

Hypervisor vendor: KVM
ulimit soft: 1048576
