### ISSUE TITLE
[Bug] (Xgrammar) (v0.3.6.post1) RuntimeError: CUDA dependencies are not installed.

### ISSUE THREAD

**Issue by Quang-elec44** [sgl-project/sglang#2209]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

```
llm-sglang-dev  | Exception in thread Thread-4 (forward_thread_func):
llm-sglang-dev  | Traceback (most recent call last):
llm-sglang-dev  |   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
llm-sglang-dev  |     self.run()
llm-sglang-dev  |   File "/usr/lib/python3.10/threading.py", line 953, in run
llm-sglang-dev  |     self._target(*self._args, **self._kwargs)
llm-sglang-dev  |   File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 91, in forward_thread_func
llm-sglang-dev  |     self.forward_thread_func_()
llm-sglang-dev  |   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
llm-sglang-dev  |     return func(*args, **kwargs)
llm-sglang-dev  |   File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 118, in forward_thread_func_
llm-sglang-dev  |     logits_output, next_token_ids = self.worker.forward_batch_generation(
llm-sglang-dev  |   File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 149, in forward_batch_generation
llm-sglang-dev  |     next_token_ids = self.model_runner.sample(logits_output, model_worker_batch)
llm-sglang-dev  |   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 660, in sample
llm-sglang-dev  |     logits = self.apply_logits_bias(logits_output.next_token_logits, sampling_info)
llm-sglang-dev  |   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 685, in apply_logits_bias
llm-sglang-dev  |     sampling_info.apply_mask(logits=logits, vocab_mask=sampling_info.vocab_mask)
llm-sglang-dev  |   File "/sgl-workspace/sglang/python/sglang/srt/constrained/xgrammar_backend.py", line 94, in apply_vocab_mask
llm-sglang-dev  |     apply_token_bitmask_inplace(logits, vocab_mask)
llm-sglang-dev  |   File "/usr/local/lib/python3.10/dist-packages/xgrammar/matcher.py", line 110, in apply_token_bitmask_inplace
llm-sglang-dev  |     apply_token_bitmask_inplace_cuda(logits, bitmask, indices)
llm-sglang-dev  |   File "/usr/local/lib/python3.10/dist-packages/xgrammar/kernels/apply_token_bitmask_inplace_cuda.py", line 199, in apply_token_bitmask_inplace_cuda
llm-sglang-dev  |     raise RuntimeError(
llm-sglang-dev  | RuntimeError: CUDA dependencies are not installed. Please follow https://xgrammar.mlc.ai/docs/start/install#cuda-dependency to install CUDA dependency.
```

### Reproduction

```yaml
services:
  llm-sglang-dev:
    image: lmsysorg/sglang:latest
    container_name: llm-sglang-dev
    restart: unless-stopped
    environment:
      HUGGING_FACE_HUB_TOKEN: <my-hf-token>
    ports:
      - "8007:8007"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ipc: host
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    env_file: 
      - .env
    command: >
      python3 -m sglang.launch_server
      --model Qwen/Qwen2.5-7B-Instruct-AWQ
      --host 0.0.0.0
      --port 8007
      --api-key <my-api-key>
      --served-model-name gpt-4o
      --tensor-parallel-size 1
      --mem-fraction-static 0.4
      --random-seed 42
      --enable-p2p-check
      --show-time-cost
      --quantization awq_marlin
      --grammar-backend xgrammar
      --enable-cache-report
      --context-length 2048
```

# Python script

```python
import openai

from pydantic import BaseModel

client = openai.OpenAI(
    base_url="http://localhost:8007/v1",
    api_key=<my-api-key>
)

class Players(BaseModel):
    names: list[str]
    

completion = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "user", "content": "Give me twenty football players' name and return the result as a JSON object with the key is `names`"}
    ],
    temperature=0.0,
    max_tokens=256,
    extra_body={
        "response_format": {
            "type": "json_schema",
            "json_schema": {
                "name": Players.__name__,
                "schema": Players.model_json_schema()
            }
        }
    }
)
print(completion.choices[0].message.content)
```

### Environment

```
Python: 3.10.15 (main, Sep  7 2024, 18:35:33) [GCC 9.4.0]
CUDA available: True
GPU 0: NVIDIA A10G
GPU 0 Compute Capability: 8.6
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 550.120
PyTorch: 2.5.1+cu124
flashinfer: 0.1.6+cu121torch2.4
triton: 3.1.0
transformers: 4.46.3
torchao: 0.6.1
numpy: 1.26.4
aiohttp: 3.11.7
fastapi: 0.115.5
hf_transfer: 0.1.8
huggingface_hub: 0.26.2
interegular: 0.3.3
psutil: 6.1.0
pydantic: 2.10.1
multipart: 0.0.17
zmq: 26.2.0
uvicorn: 0.32.1
uvloop: 0.21.0
vllm: 0.6.4.post1
openai: 1.55.1
anthropic: 0.39.0
NVIDIA Topology: 
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0-47    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

Hypervisor vendor: KVM
ulimit soft: 1048576
```
