### ISSUE TITLE
[Bug] Failed to launch engine when working with Ray Serve: signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by pengye91** [sgl-project/sglang#2536]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

Hi team, I'm using SGLang with Ray Serve, and it works like a charm until I upgraded SGLang to latest version (0.4.0.post1 or from main branch).

The error is like:
```
await self._call_func_or_gen(
 File "/home/ray/ray_venv/lib/python3.10/site-packages/ray/serve/_private/replica.py", line 867, in _call_func_or_gen
 result = callable(*args, **kwargs)
 File "/home/ray/ray_venv/lib/python3.10/site-packages/ray/serve/api.py", line 219, in __init__
 cls.__init__(self, *args, **kwargs)
 File "/home/ray/working_dir/ray_serve_proxy.py", line 39, in __init__
 launch_engine(server_args)
 File "/tmp/sglang/python/sglang/srt/server.py", line 431, in launch_engine
 _set_envs_and_config(server_args)
 File "/tmp/sglang/python/sglang/srt/server.py", line 603, in _set_envs_and_config
 signal.signal(signal.SIGQUIT, sigquit_handler)
 File "/usr/local/lib/python3.10/signal.py", line 56, in signal
 handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```

and it's related to the signal handler part in the [`_set_envs_and_config`](https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/server.py#L567) function.

and it would work if I delete the signal related codes and with other codes untouched.

### Reproduction

I'm using the Ray Serve script `ray_serve_proxy.py`:

```
from sglang.srt.server import ServerArgs
from typing import Any
from sglang.srt.server import app, launch_engine, add_api_key_middleware 

from ray import serve
from ray.serve import Application


@serve.deployment(name="test", health_check_period_s=600, health_check_timeout_s=60000)
@serve.ingress(app)
class Test:
    def __init__(self, args: dict[str, Any]):
        server_args = ServerArgs(**args)
        launch_engine(server_args)

        # Add api key authorization
        if server_args.api_key:
            add_api_key_middleware(app, server_args.api_key)

def app_builder(args: ServerArgs) -> Application:
    return Test.bind(args)
```

with the serve config `test.yaml`:

```
proxy_location: EveryNode
http_options:
  host: 0.0.0.0
  port: 8000
grpc_options:
  port: 9000
  grpc_servicer_functions: []
logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true
applications:
  - name: app1
    import_path: ray_serve_proxy:app_builder
    runtime_env:
      env_vars:
        TORCH_CUDA_ARCH_LIST: "8.0 8.9"
    args:
      tp_size: 4
      dtype: "auto"
      model_path: "Qwen/Qwen2.5-72B-Instruct-GPTQ-Int4"
      log_level: "debug"
      chunked_prefill_size: 8192
      enable_p2p_check: false
      mem_fraction_static: 0.7
    deployments:
      - name: test
        max_ongoing_requests: 1024
        autoscaling_config:
          min_replicas: 2
          initial_replicas: 2
          max_replicas: 2
          target_num_ongoing_requests_per_replica: 10.0
          metrics_interval_s: 10.0
          look_back_period_s: 30.0
          smoothing_factor: 1.0
          upscale_smoothing_factor: null
          downscale_smoothing_factor: null
          downscale_delay_s: 600.0
          upscale_delay_s: 30.0
        ray_actor_options:
          num_cpus: 64
          num_gpus: 4
```

the command is `serve run test.yaml`

### Environment

python3 -m sglang.check_env
/root/miniconda3/lib/python3.12/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
Python: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
GPU 0,1,2,3,4,5,6,7 Compute Capability: 7.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.6, V12.6.20
CUDA Driver Version: 535.104.12
PyTorch: 2.4.0+cu121
sglang: 0.4.0.post1
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.45.2
torchao: Module Not Found
numpy: 1.26.4
aiohttp: 3.10.5
fastapi: 0.114.1
hf_transfer: 0.1.8
huggingface_hub: 0.24.7
interegular: 0.3.3
modelscope: Module Not Found
orjson: Module Not Found
packaging: 24.1
psutil: 6.0.0
pydantic: 2.9.1
multipart: 0.0.9
zmq: 26.2.0
uvicorn: 0.30.6
uvloop: 0.20.0
vllm: Module Not Found
xgrammar: Module Not Found
openai: 1.44.1
anthropic: 0.34.2
decord: 0.6.0
NVIDIA Topology:
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	NIC1	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV1	NV2	NV1	SYS	SYS	SYS	NV2	SYS	SYS	0-23,48-71	0		N/A
GPU1	NV1	 X 	NV1	NV2	SYS	SYS	NV2	SYS	SYS	SYS	0-23,48-71	0		N/A
GPU2	NV2	NV1	 X 	NV2	SYS	NV1	SYS	SYS	SYS	SYS	0-23,48-71	0		N/A
GPU3	NV1	NV2	NV2	 X 	NV1	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0		N/A
GPU4	SYS	SYS	SYS	NV1	 X 	NV2	NV2	NV1	NODE	NODE	24-47,72-95	1		N/A
GPU5	SYS	SYS	NV1	SYS	NV2	 X 	NV1	NV2	NODE	NODE	24-47,72-95	1		N/A
GPU6	SYS	NV2	SYS	SYS	NV2	NV1	 X 	NV1	PIX	PIX	24-47,72-95	1		N/A
GPU7	NV2	SYS	SYS	SYS	NV1	NV2	NV1	 X 	PIX	PIX	24-47,72-95	1		N/A
NIC0	SYS	SYS	SYS	SYS	NODE	NODE	PIX	PIX	 X 	PIX
NIC1	SYS	SYS	SYS	SYS	NODE	NODE	PIX	PIX	PIX	 X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1

ulimit soft: 1048576
