### ISSUE TITLE
prometheus query return no result

### ISSUE THREAD

**Issue by 315930399** [sgl-project/sglang#2677]
Hi, thank you for your great work. I'm new to Prometheus and Grafana and I'd like to use sglang with them.  After I set up according to the [document](https://sgl-project.github.io/references/production_metrics.html#../examples/monitoring/grafana.json), the dashboards show no data. 
![微信图片_20241231141427](https://github.com/user-attachments/assets/d4cac92b-d6e8-40d7-b15d-d8b4473f009a)
I tried to query in prometheus directly with expr in [example](https://github.com/sgl-project/sglang/blob/main/examples/monitoring/grafana.json), no result as well.
![微信图片_20241231142210](https://github.com/user-attachments/assets/e67364db-ef84-42e3-bf12-af4915a1146a)
please help me out

**Comment by merrymercy** [comment]
Some documentation is outdated. Does this work for you?
```
curl http://localhost:30000/metrics
```

cc @binarycrayon for the fix.

**Comment by 315930399** [comment]
I think this grafana [example](https://github.com/sgl-project/sglang/blob/main/examples/monitoring/grafana.json) need update

**Comment by binarycrayon** [comment]
I will fix it

**Comment by zhaochenyang20** [comment]
@binarycrayon Thanks so much for help!

**Comment by Swipe4057** [comment]
@binarycrayon @merrymercy I am following the instructions exactly as specified in the documentation at https://docs.sglang.ai/references/production_metrics.html#../examples/monitoring/grafana.json to set up the metrics, but I am getting "No data" everywhere. Initially, I configured everything as described in the instructions, but it didn't work. Then I checked with `curl http://localhost:30000/metrics`, and it works, printing the metrics.

Currently, I have the following configurations:

**compose.yaml for LLM:**

```yaml
services:
  sglang:
    image: lmsysorg/sglang:v0.4.2-cu124
    container_name: sglang_v0.4.2_cu124
    volumes:
      - /data/models:/data/models
    restart: always
    network_mode: host  
    entrypoint: python3 -m sglang.launch_server
    command: 
      --model-path ***
      --served-model-name ***
      --port 30000
      --host 0.0.0.0
      --mem-fraction-static 0.88
      --context-length 32768
      --quantization awq_marlin
      --schedule-conservativeness 0.3
      --grammar-backend xgrammar
      --constrained-json-whitespace-pattern "[\n\t ]*"
      --enable-torch-compile
      --max-running-requests 64
      --enable-mixed-chunk
      --chunked-prefill-size 2048
      --disable-overlap
      --schedule-policy fcfs
      --enable-metrics
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:30000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
```

**docker-compose.yaml for metrics:**

```yaml
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    restart: always
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    env_file: .env
```

**prometheus.yaml:**

```yaml
# prometheus.yaml
global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: sglang
    static_configs:
      - targets:
          - '127.0.0.1:30000/metrics'
```

In `grafana.json`, I have replaced this part:

```json
{
  "current": {
    "selected": false,
    "text": "127.0.0.1:30000/metrics",
    "value": "127.0.0.1:30000/metrics"
  }
}
```

But still, nothing works. Can you tell me where the mistake is? I can't set it up according to the documentation.
