### ISSUE TITLE
How to return reasoning_content from sglang server response?

### ISSUE THREAD

**Issue by zengqingfu1442** [sgl-project/sglang#3428]
I use docker-compose to deploy locally
```
services:
  sglang1:
    image: lmsysorg/sglang:latest
    container_name: sglang-DeepSeek-R1-Distill-Qwen-7B
    volumes:
      - /root/DeepSeek-R1-Distill-Qwen-7B:/DeepSeek-R1-Distill-Qwen-7B
      # If you use modelscope, you need mount this directory
      # - ${HOME}/.cache/modelscope:/root/.cache/modelscope
    restart: always
    #network_mode: host
    # Or you can only publish port 30000
    ports:
      - 30000:30000
    environment:
      # if you use modelscope to download model, you need set this environment
      SGLANG_USE_MODELSCOPE: true
    entrypoint: python3 -m sglang.launch_server
    command:
      --model-path /DeepSeek-R1-Distill-Qwen-7B/
      --host 0.0.0.0
      --port 30000
      --served-model-name deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
      --grammar-backend xgrammar
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:30000/health || exit 1"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
```
but the response doesn't contain the "reasoning_content".

![Image](https://github.com/user-attachments/assets/1c0fdfa2-9a2a-4a8f-8149-e6f96fc776c7)
