### ISSUE TITLE
[Bug] SGLang Tool Calling for Qwen2.5 models returns empty ChatCompletionMessage content

### ISSUE THREAD

**Issue by Superskyyy** [sgl-project/sglang#3797]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

So the story is I deployed a Qwen2.5-72B-Instruct model with SGLang on 8 cards, been testing the tool calling agents with LangGraph. The agents do not output any content when it decides to call a tool, therefore it just decides to randomly call tools until it suddenly stops. The behavior has led to very poor agentic performance.

On vLLM side, an agent tool call is accompanied by justifications and it will not randomly decide to call/not call a tool without justifications.

### Reproduction

The tool call interface simply makes LLM response content to None therefore a ReAct style agent will perform poorly. 

### Environment

INFO 02-24 01:40:19 __init__.py:190] Automatically detected platform cuda.
Python: 3.12.8 (main, Jan 27 2025, 17:53:37) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 550.127.05
PyTorch: 2.5.1+cu124
sgl_kernel: 0.0.3.post6
flashinfer: 0.2.1.post2+cu124torch2.5
triton: 3.1.0
transformers: 4.48.3
torchao: 0.8.0
numpy: 1.26.4
aiohttp: 3.11.12
fastapi: 0.115.8
hf_transfer: 0.1.9
huggingface_hub: 0.29.0
interegular: 0.3.3
modelscope: 1.23.0
orjson: 3.10.15
packaging: 24.2
psutil: 7.0.0
pydantic: 2.10.6
multipart: 0.0.20
zmq: 26.2.1
uvicorn: 0.34.0
uvloop: 0.21.0
vllm: 0.7.2
openai: 1.63.2
tiktoken: 0.9.0
anthropic: 0.46.0
decord: 0.6.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    NIC8    CPU Affinity  NUMA Affinity    GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    0-55,112-167  0N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE    0-55,112-167  0N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    0-55,112-167  0N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    0-55,112-167  0N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     56-111,168-2231N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    SYS     56-111,168-2231N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    SYS     56-111,168-2231N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     SYS     56-111,168-2231N/A
NIC0    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE
NIC1    NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE    SYS     SYS     SYS     SYS     NODE
NIC2    NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE    SYS     SYS     SYS     SYS     NODE
NIC3    NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      SYS     SYS     SYS     SYS     NODE
NIC4    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    SYS
NIC5    SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE    SYS
NIC6    SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE    SYS
NIC7    SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      SYS
NIC8    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_5
  NIC4: mlx5_6
  NIC5: mlx5_7
  NIC6: mlx5_8
  NIC7: mlx5_9
  NIC8: mlx5_bond_0

ulimit soft: 1048576

**Comment by zhaochenyang20** [comment]
@Superskyyy Thanks for pointing this out. We think if you can not provide us a script to reproduce your error, then it does not make sense for us to debug it. In the meantime, your story is good. I see you have one repo named:

https://github.com/Superskyyy/How-To-Ask-Questions-The-Smart-Way

Please ask your question in a smart way. And, you can contact my WeChat for further discussion. 18015766633

**Comment by Superskyyy** [comment]
@zhaochenyang20 My bad, was in a hurry to open the issue before I went out earlier.

This issue should really relate to [issue](https://github.com/sgl-project/sglang/issues/3637#issuecomment-2676014767) where I posted details of the unexpected outputs from SGLang. 

So initially I thought the None or "" content was an expected behavior when tool-call was involved, but later I found both OpenAI (GPT-4o) and vLLM (Qwen2.5 72B) acts differently than the SGLang tool calling. 

I will post reproducible examples in a bit.

**Comment by Superskyyy** [comment]
Starting the servers `docker-compose.yaml`
```
# This is a common compose file for sglang and vllm
services:
  sglang:
    image: lmsysorg/sglang:latest
    container_name: sglang-qwen-72B-instruct
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - /home/original_models:/home/original_models
    restart: always
    network_mode: host 
    privileged: true 
    entrypoint: python3 -m sglang.launch_server
    command: --model-path /home/original_models/Qwen2.5-72B-Instruct
      --host localhost
      --port 7200
      --api-key=xxxxx
      --tool-call-parser qwen25
      --tp 8
      --enable-torch-compile
      --torch-compile-max-bs 8
      --context-length 32768
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7200/health || exit 1"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0,1,2,3,4,5,6,7"]
              capabilities: [gpu]

  vllm-server:
    image: vllm/vllm-openai:latest 
    container_name: vllm-qwen-72B-instruct
    command: >
      --model /home/original_models/Qwen2.5-72B-Instruct 
      --tensor-parallel-size 8 
      --enable-chunked-prefill 
      --enable-prefix-caching 
      --enable-auto-tool-choice 
      --tool-call-parser hermes 
      --api-key xxxxx
      --host localhost --port 7200
    restart: unless-stopped
    privileged: true
    network_mode: host
    ipc: host
    volumes:
      - /home/original_models:/home/original_models 
      - cache:/workspace/.cache
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0,1,2,3,4,5,6,7"]
              capabilities: [gpu]
volumes:
  cache:
````

Client code:

```
import openai

def get_current_temperature(location: str, unit: str = "celsius"):
    """Get current temperature at a location.

    Args:
        location: The location to get the temperature for, in the format "City, State, Country".
        unit: The unit to return the temperature in. Defaults to "celsius". (choices: ["celsius", "fahrenheit"])

    Returns:
        the temperature, the location, and the unit in a dict
    """
    return {
        "temperature": 26.1,
        "location": location,
        "unit": unit,
    }


def get_function_by_name(name):
    if name == "get_current_temperature":
        return get_current_temperature

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_current_temperature",
            "description": "Get current temperature at a location.",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": 'The location to get the temperature for, in the format "City, State, Country".',
                    },
                    "unit": {
                        "type": "string",
                        "enum": ["celsius", "fahrenheit"],
                        "description": 'The unit to return the temperature in. Defaults to "celsius".',
                    },
                },
                "required": ["location"],
            },
        },
    },
]
MESSAGES = [
    {"role": "system", "content": "You are Qwen, created by Alibaba Cloud. You are a helpful assistant.\n\nCurrent Date: 2024-09-30"},
    {"role": "user",  "content": "What's the temperature in San Francisco now? Think before act, then use the tools to help you."},
]

client = openai.Client(
    base_url="http://localhost:7200/v1", 
    api_key="xxxxxx"
)

response = client.chat.completions.create(
    model='/home/original_models/Qwen2.5-72B-Instruct',
    messages=MESSAGES,
    tools=TOOLS,
)

print(response.choices[0].message.content)
print(response.choices[0].message.tool_calls)

```

vLLM Output: (**Notice there's an actual "think" content**)
```
To provide you with the current temperature in San Francisco, I need to use the `get_current_temperature` function. I'll request the temperature in Celsius, and if you prefer Fahrenheit, I can convert it for you. Let me fetch the data.

[ChatCompletionMessageToolCall(id='chatcmpl-tool-d498fbd8a64d491fae5555d4a026beb7', function=Function(arguments='{"location": "San Francisco, California, USA", "unit": "celsius"}', name='get_current_temperature'), type='function')]
```


SGLang Output:
```
None
[ChatCompletionMessageToolCall(id='0', function=Function(arguments='{"location": "San Francisco, California, USA", "unit": "celsius"}', name='get_current_temperature'), type='function')]
```

GPT-4O (OpenAI Endpoint)

```
To find out the current temperature in San Francisco, I will use a function that provides real-time weather information. I'll proceed with calling the appropriate function to get this data for you.
[ChatCompletionMessageToolCall(id='call_ByAinAtfBtweEsnjY6piV0qi', function=Function(arguments='{"location":"San Francisco, California, USA"}', name='get_current_temperature'), type='function')]
```
