### ISSUE TITLE
[Bug] After using --enable-torch-compile, garbled output

### ISSUE THREAD

**Issue by echozyr2001** [sgl-project/sglang#3944]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

In commit(71ed018), --enable-torch-compile will cause garbled output. Without --enable-torch-compile, the output is normal.

Update: In the latest commit (ec0a72c) this issue still exists.

### enable torch compile

![Image](https://github.com/user-attachments/assets/b77c5127-2566-40d8-a72b-202fbe0d2a27)

### disable torch compile

![Image](https://github.com/user-attachments/assets/781d34f1-a646-41ed-83b5-2b4c49cce345)

Also, if I don't set max_tokens, when --enable-torch-compile, the output will not stop, and it will keep outputting more than a million tokens, causing Postman to crash.

### Reproduction

Below is the compose file where I start the server

Node1

```yaml
services:
  r1-1-sg:
    container_name: r1-1-sg
    image: sglang:latest
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "1024g"
    ipc: "host"
    network_mode: "host"
    volumes:
      - /data/deepseek-r1:/root/deepseek-r1
      - /data/torchcache-r1:/root/torchcache
      - /data/r1-nextn:/root/r1-nextn
    environment:
      - GLOO_SOCKET_IFNAME=ens12f0np0
      - NCCL_SOCKET_IFNAME=ibs1
      - NCCL_IB_ALLOW=1
      - NCCL_IB_DISABLE=0
      - NCCL_IB_CUDA_SUPPORT=1
      - NCCL_IB_HCA=ibp
      - NCCL_IB_RETRY_CNT=13
      - NCCL_IB_GID_INDEX=3
      - NCCL_NET_GDR_LEVEL=2
      - NCCL_IB_TIMEOUT=22
      - NCCL_DEBUG=INFO
      - NCCL_P2P_LEVEL=NVL
      - NCCL_CROSS_NIC=1
      - NCCL_NET_GDR_LEVEL=SYS
      - TORCHINDUCTOR_CACHE_DIR=/root/torchcache
    command: >
      python3 -m sglang.launch_server
      --attention-backend flashinfer
      --model-path /root/deepseek-r1
      --dist-init-addr 10.0.251.41:50000
      --host 0.0.0.0
      --port 30000
      --tp 16
      --nnodes 2
      --node-rank 0
      --trust-remote-code
      --context-length 65536
      --chunked-prefill-size 32768
      --max-prefill-tokens 32768
      --schedule-conservativeness 0.1
      --mem-fraction-static 0.8
      --schedule-policy dfs-weight
      --enable-torch-compile
      --torch-compile-max-bs 8
    restart: always
```

Node2

```yaml
services:
  r1-2-sg:
    container_name: r1-2-sg
    image: sglang:latest
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "1024g"
    ipc: "host"
    network_mode: "host"
    volumes:
      - /data/deepseek-r1:/root/deepseek-r1
      - /data/torchcache-r1:/root/torchcache
      - /data/r1-nextn:/root/r1-nextn
    environment:
      - GLOO_SOCKET_IFNAME=ens12f0np0
      - NCCL_SOCKET_IFNAME=ibs1
      - NCCL_IB_ALLOW=1
      - NCCL_IB_DISABLE=0
      - NCCL_IB_CUDA_SUPPORT=1
      - NCCL_IB_HCA=ibp
      - NCCL_IB_RETRY_CNT=13
      - NCCL_IB_GID_INDEX=3
      - NCCL_NET_GDR_LEVEL=2
      - NCCL_IB_TIMEOUT=22
      - NCCL_DEBUG=INFO
      - NCCL_P2P_LEVEL=NVL
      - NCCL_CROSS_NIC=1
      - NCCL_NET_GDR_LEVEL=SYS
      - TORCHINDUCTOR_CACHE_DIR=/root/torchcache
    command: >
      python3 -m sglang.launch_server
      --attention-backend flashinfer
      --model-path /root/deepseek-r1
      --dist-init-addr 10.0.251.41:50000
      --host 0.0.0.0
      --port 30000
      --tp 16
      --nnodes 2
      --node-rank 1
      --trust-remote-code
      --context-length 65536
      --chunked-prefill-size 32768
      --max-prefill-tokens 32768
      --schedule-conservativeness 0.1
      --mem-fraction-static 0.8
      --schedule-policy dfs-weight
      --enable-torch-compile
      --torch-compile-max-bs 8
    restart: always
```

Here is the request sent

```json
{
    "model": "deepseek/deepseek-r1",
    "messages": [
        {
            "role": "user",
            "content": "What is the weather like in Paris today?"
        }
    ],
    "max_tokens": 1400,
    "stream": false
}
```

### Environment

```bash
Python: 3.10.12 (main, Jan 17 2025, 14:35:34) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H20
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 565.57.01
PyTorch: 2.5.1+cu124
sgl_kernel: 0.0.3.post6
flashinfer: 0.2.1.post2+cu124torch2.5
triton: 3.1.0
transformers: 4.48.3
torchao: 0.8.0
numpy: 1.26.4
aiohttp: 3.11.12
fastapi: 0.115.8
hf_transfer: 0.1.9
huggingface_hub: 0.28.1
interegular: 0.3.3
modelscope: 1.23.0
orjson: 3.10.15
packaging: 24.2
psutil: 7.0.0
pydantic: 2.10.6
multipart: 0.0.20
zmq: 26.2.1
uvicorn: 0.34.0
uvloop: 0.21.0
vllm: 0.7.2
openai: 1.63.2
tiktoken: 0.9.0
anthropic: 0.45.2
decord: 0.6.0
NVIDIA Topology:
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    CPU Affinity    NUMA Affinity  GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    PIX     NODE    SYS     SYS     NODE    NODE    SYS     SYS     0-55,112-167    0     N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    NODE    NODE    SYS     SYS     NODE    NODE    SYS     SYS     0-55,112-167    0     N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    NODE    PIX     SYS     SYS     NODE    NODE    SYS     SYS     0-55,112-167    0     N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    NODE    NODE    SYS     SYS     NODE    NODE    SYS     SYS     0-55,112-167    0     N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     SYS     PIX     NODE    SYS     SYS     NODE    NODE    56-111,168-223  1     N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     SYS     NODE    NODE    SYS     SYS     NODE    NODE    56-111,168-223  1     N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     SYS     NODE    PIX     SYS     SYS     NODE    NODE    56-111,168-223  1     N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     SYS     NODE    NODE    SYS     SYS     NODE    NODE    56-111,168-223  1     N/A
NIC0    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    SYS     SYS     NODE    NODE    SYS     SYS
NIC1    NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE     X      SYS     SYS     NODE    NODE    SYS     SYS
NIC2    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     SYS      X      NODE    SYS     SYS     NODE    NODE
NIC3    SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    SYS     SYS     NODE     X      SYS     SYS     NODE    NODE
NIC4    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    NODE    SYS     SYS      X      PIX     SYS     SYS
NIC5    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    NODE    SYS     SYS     PIX      X      SYS     SYS
NIC6    SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    SYS     SYS     NODE    NODE    SYS     SYS      X      PIX
NIC7    SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    SYS     SYS     NODE    NODE    SYS     SYS     PIX      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: ibp14s0
  NIC1: ibp71s0
  NIC2: ibp134s0
  NIC3: ibp195s0
  NIC4: rocep31s0f0
  NIC5: rocep31s0f1
  NIC6: rocep153s0f0
  NIC7: rocep153s0f1


ulimit soft: 1048576
```
