### ISSUE TITLE
[Bug] Unable to deploy with CPUs without AVX

### ISSUE THREAD

**Issue by Quang-elec44** [sgl-project/sglang#6025]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

I got the following error when deploying `sglang` using Docker.

```shell
ERROR: This container was built for CPUs supporting at least the AVX instruction set, but
       the CPU detected was QEMU Virtual CPU version 2.5+, which does not report
       support for AVX.  An Illegal Instruction exception at runtime is likely to result.
       See https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX .
```

There is no problem with `vllm`

### Reproduction

Here is the `docker-compose.yaml` file:

```yaml
services:
  llm-sglang:
    image: lmsysorg/sglang:latest
    container_name: llm-sglang
    restart: unless-stopped
    environment:
      HUGGING_FACE_HUB_TOKEN: ${HF_TOKEN}
    ports:
      - "${PORT}:${PORT}"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1', '2', '3']
            capabilities: [gpu]
    ipc: host
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    networks:
      - ai-assistant
    env_file: 
      - .env
    command: >
      python3 -m sglang.launch_server
      --host 0.0.0.0
      --model ${MODEL}
      --port ${PORT}
      --api-key ${API_KEY}
      --served-model-name ${SERVED_MODEL_NAME}
      --tensor-parallel-size ${TP}
      --mem-fraction-static ${MFS}
      --context-length ${CONTEXT_LENGTH}
      --random-seed 42
      --enable-p2p-check
      --quantization awq_marlin
      --enable-cache-report
      --show-time-cost
      --grammar-backend outlines
      --constrained-json-whitespace-pattern "[\n\t ]*"

networks:
  ai-assistant:
    external: true
```

```shell
# .env
HF_TOKEN=<my-hf-token>
PORT=8013
MAX_MODEL_LEN=32768
TP=2
GMU=0.8
SERVED_MODEL_NAME=gpt-4o
MODEL=Qwen/Qwen3-14B-AWQ
API_KEY=<my-api-key>
```

### Environment

```
Python: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA A30
GPU 0,1,2,3 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 550.120
PyTorch: 2.6.0+cu124
sglang: 0.4.6.post2
sgl_kernel: 0.1.1
flashinfer_python: 0.2.5+cu124torch2.6
triton: 3.2.0
transformers: 4.51.1
torchao: 0.10.0
numpy: 2.2.5
aiohttp: 3.11.18
fastapi: 0.115.12
hf_transfer: 0.1.9
huggingface_hub: 0.30.2
interegular: 0.3.3
modelscope: 1.25.0
orjson: 3.10.18
outlines: 0.1.11
packaging: 25.0
psutil: 7.0.0
pydantic: 2.11.4
python-multipart: 0.0.20
pyzmq: 26.4.0
uvicorn: 0.34.2
uvloop: 0.21.0
vllm: Module Not Found
xgrammar: 0.1.17
openai: 1.76.2
tiktoken: 0.9.0
anthropic: 0.50.0
litellm: 1.67.5
decord: 0.6.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PHB     PHB     PHB     0-89    0               N/A
GPU1    PHB      X      PHB     PHB     0-89    0               N/A
GPU2    PHB     PHB      X      PHB     0-89    0               N/A
GPU3    PHB     PHB     PHB      X      0-89    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

Hypervisor vendor: KVM
ulimit soft: 1048576
```
