### ISSUE TITLE
[Bug] Why isn't the enable_thinking parameter in sglang working as expected?

### ISSUE THREAD

**Issue by chelseaztq** [sgl-project/sglang#6529]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

My sglang version is 0.4.6-post4.

The Docker-compose startup command for sglang is:

```yaml
version: '3.9'

services:
  Sglang_server:
    image: docker.1ms.run/lmsysorg/sglang:v0.4.6.post4-cu124
    shm_size: '10gb'
    runtime: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=6,7
    volumes:
      - /data/sdv1/model:/model
    ports:
      - "8011:8000"
    entrypoint: ["python3"]
    command: [
      "-m",
      "sglang.launch_server",
      "--model-path",
      "/model/Qwen/Qwen3-32B",
      "--port", "8000",
      "--host","0.0.0.0",
      "--api-key", "ShuZhiLian@123",
      "--random-seed", "2024",
      "--mem-fraction", "0.6",
      "--served-model-name", "Sglang-Qwen3-32B",
      "--tp", "2",
      "--chunked-prefill-size","4096",
      "--reasoning-parser","qwen3",
    ]
```

My cURL request test and results are as follows:

curl -X POST "http://x.x.x.x:8888/v1/chat/completions"   -H "Content-Type: application/json"   -H "Authorization: Bearer xxx"   -d '{
    "model": "Sglang-Qwen3-32B",
    "messages": [
      {
        "role": "user",
        "content": "Give me a short introduction to large language models"
      }
    ],
    "max_tokens": 8192,
    "temperature": 0.7,
    "top_p": 0.8,
    "presence_penalty": 1.5,
    "top_k": 20,
    "chat_template_kwargs": {
      "enable_thinking": false
    }
  }'
{"id":"ae1f02b6b2ab49879664c605b3ee6e59","object":"chat.completion","created":1747915566,"model":"Sglang-Qwen3-32B","choices":[{"index":0,"message":{"role":"assistant","content":"**Introduction to Large Language Models (LLMs):**\n\nLarge Language Models (LLMs) are advanced artificial intelligence systems designed to understand, generate, and interact with human language. Trained on vast amounts of textual data from the internet, books, articles, and other sources, these models learn intricate patterns, grammar, semantics, and contextual relationships in language. They leverage **deep learning** techniques, particularly **transformer-based architectures**, which use self-attention mechanisms to efficiently process and relate different parts of an input sequence.\n\n### Key Features:\n1. **Training Process**:  \n   - LLMs undergo **pre-training** on diverse datasets to develop general language skills (e.g., predicting the next word in a sentence).  \n   - They may later be **fine-tuned** for specific tasks (e.g., answering questions, coding, or summarization).\n\n2. **Capabilities**:  \n   - Generate coherent text (e.g., stories, emails, code).  \n   - Translate languages, answer questions, and perform reasoning.  \n   - Adapt to various roles (chatbots, virtual assistants, creative tools).\n\n3. **Applications**:  \n   - Customer service automation, education, healthcare, and research.  \n   - Content creation, software development, and data analysis.\n\n4. **Challenges**:  \n   - **Ethics & Bias**: May reflect biases in training data or produce harmful outputs.  \n   - **Transparency**: Often operate as \"black boxes,\" making decision-making opaque.  \n   - **Resource Intensity**: Require massive computational power and energy.\n\n5. **Limitations**:  \n   - LLMs lack true understanding or consciousness; they rely on statistical patterns.  \n   - Outputs can be inaccurate, hallucinated, or contextually inappropriate.\n\n### Future Outlook:  \nLLMs continue to evolve, driving innovations in AI while raising critical discussions about responsible use, privacy, and societal impact. As the technology advances, balancing utility with ethical considerations remains a priority.","reasoning_content":"Okay, the user is asking for a short introduction to large language models. Let me start by recalling what I know about this topic. Large language models (LLMs) are a type of AI that processes and generates human-like text. They're trained on massive datasets, right? So first, I should define them clearly.\n\nI need to mention their training process—probably using techniques like deep learning with transformer architectures. Transformers use attention mechanisms, which help the model focus on relevant parts of the input. That's important because it explains why they're effective at handling long-range dependencies in text.\n\nNext, their applications. Users might be interested in real-world uses, so examples like chatbots, translation, content creation, and code generation would be good. Also, maybe touch on their ability to answer questions or perform tasks without explicit programming.\n\nI should also address some challenges. Ethical concerns like bias in training data, potential misuse, and environmental impact from high computational needs. It's important to present a balanced view, not just the positives but also the issues.\n\nThe user wants a short intro, so I need to keep it concise but informative. Avoid jargon where possible, but terms like \"transformer architecture\" are necessary. Maybe explain those briefly. Also, make sure the flow is logical: definition, how they work, applications, challenges, and future outlook.\n\nWait, the user might be a student or someone new to AI, so clarity is key. Let me check if I'm missing any key points. Oh, maybe mention pre-training and fine-tuning stages. Pre-training on vast data and then fine-tuning for specific tasks. That helps in understanding their adaptability.\n\nAlso, note that they can generate coherent text but don't truly understand context. Highlighting the difference between statistical patterns and actual comprehension could be useful.\n\nLet me structure this step by step. Start with a definition, then training method, architecture, applications, challenges, and conclusion. Keep each section brief. Make sure to connect the dots so the reader understands the significance of LLMs in current tech.\n","tool_calls":null},"logprobs":null,"finish_reason":"stop","matched_stop":151645}],"usage":{"prompt_tokens":17,"total_tokens":840,"completion_tokens":823,"prompt_tokens_details":null}}

### Reproduction

 See above for reference.

### Environment

 See above for reference.
