### ISSUE TITLE
[Bug] Container v0.4.7.post1 | ModuleNotFoundError: No module named 'vllm'

### ISSUE THREAD

**Issue by QIN2DIM** [sgl-project/sglang#7299]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

Error when starting `Qwen/Qwen3-30B-A3B` in the `lmsysorg/sglang:v0.4.7.post1-cu124` image.

There were no errors when using `lmsysorg/sglang:v0.4.6.post5-cu124` previously.

![Image](https://github.com/user-attachments/assets/2a98b5db-431c-49b0-a616-5b76a9dec8ea)

### Reproduction

**docker-compose.yaml:**
```yaml
# https://docs.sglang.ai/backend/server_arguments.html
name: sglang-Qwen3-30B-A3B
services:
  sglang:
    # => image: lmsysorg/sglang:v0.4.7.post1-cu124
    image: lmsysorg/sglang:latest
    container_name: sglang-Qwen3-30B-A3B
    volumes:
      - ${HF_HOME}:/root/.cache/huggingface
      - ${MODELSCOPE_CACHE}:/root/.cache/modelscope
      - ./inductor_root_cache:/root/inductor_root_cache
    restart: always
    ports:
      - 30000:30000
    environment:
      HF_TOKEN: ${MY_TOKEN}
      HTTPS_PROXY: http://192.168.1.53:2088
      HTTP_PROXY: http://192.168.1.53:2088
      TORCHINDUCTOR_CACHE_DIR: /root/inductor_root_cache
      NO_PROXY: 0.0.0.0,localhost,127.0.0.1
    entrypoint: python3 -m sglang.launch_server
    command:
      --model-path Qwen/Qwen3-30B-A3B
      --tp 4
      --host 0.0.0.0
      --port 30000
      --trust-remote-code
      --mem-fraction-static 0.85
      --max-running-requests 200
      --tool-call-parser qwen25
      --reasoning-parser qwen3
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:30000/health || exit 1"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
```

### Environment

```bash
(dev) root@x:/sglang/qwen3-30b-a3b# docker run -it --rm lmsysorg/sglang:v0.4.7.post1-cu124 bash

==================================
== Triton Inference Server Base ==
==================================

NVIDIA Release 24.12 (build 128719878)

Copyright (c) 2018-2024, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: CUDA Forward Compatibility mode ENABLED.
  Using CUDA 12.6 driver version 560.35.05 with kernel driver version 550.54.15.
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

root@66a61c55d738:/sgl-workspace# python3 -m sglang.check_env
Python: 3.12.3 (main, May 26 2025, 18:50:19) [GCC 13.3.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA A100-SXM4-40GB
GPU 0,1,2,3 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.6, V12.6.85
CUDA Driver Version: 550.54.15
PyTorch: 2.7.1+cu126
sglang: 0.4.7.post1
sgl_kernel: 0.1.9
flashinfer_python: 0.2.6.post1
triton: 3.3.1
transformers: 4.52.3
torchao: 0.9.0
numpy: 2.3.0
aiohttp: 3.12.13
fastapi: 0.115.12
hf_transfer: 0.1.9
huggingface_hub: 0.33.0
interegular: 0.3.3
modelscope: 1.27.0
orjson: 3.10.18
outlines: 0.1.11
packaging: 25.0
psutil: 7.0.0
pydantic: 2.11.7
python-multipart: 0.0.20
pyzmq: 27.0.0
uvicorn: 0.34.3
uvloop: 0.21.0
vllm: Module Not Found
xgrammar: 0.1.19
openai: 1.87.0
tiktoken: 0.9.0
anthropic: 0.54.0
litellm: 1.72.6
decord: 0.6.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    NIC0    NIC1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     SYS     SYS     SYS     SYS     0-35,72-107     0               N/A
GPU1    SYS      X      SYS     SYS     SYS     SYS     0-35,72-107     0               N/A
GPU2    SYS     SYS      X      SYS     SYS     SYS     36-71,108-143   1               N/A
GPU3    SYS     SYS     SYS      X      SYS     SYS     36-71,108-143   1               N/A
NIC0    SYS     SYS     SYS     SYS      X      PIX
NIC1    SYS     SYS     SYS     SYS     PIX      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1


ulimit soft: 1048576
```
