### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by fireblade2534** [sgl-project/sglang#7407]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

When I run it I get this error:

```
sglang            | [2025-06-21 00:33:52 TP1] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
sglang            | [2025-06-21 00:33:52 TP1] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
sglang            | [2025-06-21 00:33:52 TP0] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
sglang            | [2025-06-21 00:33:53 TP0] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
sglang            | [2025-06-21 00:33:53 TP0] Attention backend not set. Use flashinfer backend by default.
sglang            | [2025-06-21 00:33:53 TP0] Init torch distributed begin.
sglang            | [2025-06-21 00:33:53 TP0] sglang is using nccl==2.26.2
sglang            | [2025-06-21 00:33:54 TP0] generating GPU P2P access cache in /root/.cache/sglang/gpu_p2p_access_cache_for_0,1.json
sglang            | [2025-06-21 00:34:01 TP0] reading GPU P2P access cache from /root/.cache/sglang/gpu_p2p_access_cache_for_0,1.json
sglang            | [2025-06-21 00:34:01 TP0] Custom allreduce is disabled because your platform lacks GPU P2P capability or P2P test failed. To silence this warning, specify disable_custom_all_reduce=True explicitly.
sglang            | [2025-06-21 00:34:01 TP1] reading GPU P2P access cache from /root/.cache/sglang/gpu_p2p_access_cache_for_0,1.json
sglang            | [2025-06-21 00:34:01 TP1] Custom allreduce is disabled because your platform lacks GPU P2P capability or P2P test failed. To silence this warning, specify disable_custom_all_reduce=True explicitly.
sglang            | [2025-06-21 00:34:01 TP0] Init torch distributed ends. mem usage=0.12 GB
sglang            | [2025-06-21 00:34:01 TP1] The memory capacity is unbalanced. Some GPUs may be occupied by other processes. min_per_gpu_memory=15.59259033203125, local_gpu_memory=19.28033447265625, local_gpu_memory * 0.9=17.352301025390627
sglang            | [2025-06-21 00:34:02 TP0] Load weight begin. avail mem=15.59 GB
sglang            | [2025-06-21 00:34:02 TP0] Scheduler hit an exception: Traceback (most recent call last):
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2546, in run_scheduler_process
sglang            |     scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, pp_rank, dp_rank)
sglang            |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 312, in __init__
sglang            |     self.tp_worker = TpWorkerClass(
sglang            |                      ^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 64, in __init__
sglang            |     self.worker = TpModelWorker(
sglang            |                   ^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 78, in __init__
sglang            |     self.model_runner = ModelRunner(
sglang            |                         ^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 212, in __init__
sglang            |     self.initialize(min_per_gpu_memory)
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 253, in initialize
sglang            |     self.load_model()
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 547, in load_model
sglang            |     self.model = get_model(
sglang            |                  ^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_loader/__init__.py", line 22, in get_model
sglang            |     return loader.load_model(
sglang            |            ^^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_loader/loader.py", line 376, in load_model
sglang            |     model = _initialize_model(
sglang            |             ^^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_loader/loader.py", line 150, in _initialize_model
sglang            |     quant_config = _get_quantization_config(
sglang            |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_loader/loader.py", line 117, in _get_quantization_config
sglang            |     quant_config = get_quant_config(
sglang            |                    ^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_loader/weight_utils.py", line 136, in get_quant_config
sglang            |     quant_cls = get_quantization_config(model_config.quantization)
sglang            |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/layers/quantization/__init__.py", line 115, in get_quantization_config
sglang            |     raise ValueError(
sglang            | ValueError: awq quantization requires some operators from vllm. Please install vllm by `pip install vllm==0.9.0.1`
sglang            | 
sglang            | [2025-06-21 00:34:02 TP1] Scheduler hit an exception: Traceback (most recent call last):
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 2546, in run_scheduler_process
sglang            |     scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, pp_rank, dp_rank)
sglang            |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 312, in __init__
sglang            |     self.tp_worker = TpWorkerClass(
sglang            |                      ^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 64, in __init__
sglang            |     self.worker = TpModelWorker(
sglang            |                   ^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/managers/tp_worker.py", line 78, in __init__
sglang            |     self.model_runner = ModelRunner(
sglang            |                         ^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 212, in __init__
sglang            |     self.initialize(min_per_gpu_memory)
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 253, in initialize
sglang            |     self.load_model()
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_executor/model_runner.py", line 547, in load_model
sglang            |     self.model = get_model(
sglang            |                  ^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_loader/__init__.py", line 22, in get_model
sglang            |     return loader.load_model(
sglang            |            ^^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_loader/loader.py", line 376, in load_model
sglang            |     model = _initialize_model(
sglang            |             ^^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_loader/loader.py", line 150, in _initialize_model
sglang            |     quant_config = _get_quantization_config(
sglang            |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_loader/loader.py", line 117, in _get_quantization_config
sglang            |     quant_config = get_quant_config(
sglang            |                    ^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/model_loader/weight_utils.py", line 136, in get_quant_config
sglang            |     quant_cls = get_quantization_config(model_config.quantization)
sglang            |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sglang            |   File "/sgl-workspace/sglang/python/sglang/srt/layers/quantization/__init__.py", line 115, in get_quantization_config
sglang            |     raise ValueError(
sglang            | ValueError: awq quantization requires some operators from vllm. Please install vllm by `pip install vllm==0.9.0.1`
sglang            | 
sglang            | [2025-06-21 00:34:02] Received sigquit from a child process. It usually means the child failed.
sglang exited with code 0
```

Awq is a supported format so I don't know why vllm is not installed in the offical sglang docker image?

### Reproduction

I used this docker compose file:
```
services:
  sglang:
    image: lmsysorg/sglang:latest
    container_name: sglang
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      # If you use modelscope, you need mount this directory
      # - ${HOME}/.cache/modelscope:/root/.cache/modelscope
      - /home/fireblade2534/models:/models
    restart: always
    network_mode: host # required by RDMA
    privileged: true # required by RDMA
    # Or you can only publish port 30000
    # ports:
    #   - 30000:30000
    environment:
      HF_TOKEN: <secret>
      SGL_DISABLE_TP_MEMORY_INBALANCE_CHECK: true
      # if you use modelscope to download model, you need set this environment
      # - SGLANG_USE_MODELSCOPE: true
    entrypoint: python3 -m sglang.launch_server
    command: --model-path /models/Qwen3-32B-AWQ
      --host 0.0.0.0
      --port 6060
      --reasoning-parser qwen3
      --tp 2
      --enable-p2p-check
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6060/health || exit 1"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```

### Environment

N/A
