### ISSUE TITLE
Performance regression: 4090 GPUs slower on v0.4.8-cu126 (was 27→20 tokens/sec, A100 unaffected)

### ISSUE THREAD

**Issue by sld** [sgl-project/sglang#7568]
Hi! After upgrading from `lmsysorg/sglang:v0.4.6.post5-cu124` to `lmsysorg/sglang:v0.4.8-cu126`, I've noticed a **significant drop in generation speed** and GPU utilization on my setup with 2x4090 (48Gb each).  
- **v0.4.6:** 27 tokens/sec, GPU usage 100%
- **v0.4.8:** 20 tokens/sec, GPU usage ~75%

No other changes were made except switching the Docker image.

On an A100 80Gb, both versions work fine — no speed or GPU usage drop.

### Environment

- **GPUs:** 2x4090 48Gb
- **Docker Compose Config:** (see below)
- **Model:** Qwen3-32B
- **nvidia-smi:**
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.57.01              Driver Version: 565.57.01      CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        On  |   00000000:16:00.0 Off |                  Off |
| 32%   37C    P8             19W /  450W |   43834MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        On  |   00000000:BE:00.0 Off |                  Off |
| 45%   40C    P8             25W /  450W |   43854MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A   2121769      C   sglang::scheduler_TP0                       43824MiB |
|    1   N/A  N/A   2121770      C   sglang::scheduler_TP1                       43844MiB |
+-----------------------------------------------------------------------------------------+
```
### docker-compose.yml

```yaml
services:
  llm:
    image: lmsysorg/sglang:v0.4.6.post5-cu124
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    entrypoint: python3 -m sglang.launch_server
    command: >
      --model /llm_models/qwen3-32b
      --host 0.0.0.0
      --port 80
      --log-requests
      --log-requests-level 2
      --show-time-cost
      --random-seed 42
      --grammar-backend llguidance
      --enable-metrics
      --tp 2
      --enable-p2p-check
      --kv-cache-dtype fp8_e5m2
      --allow-auto-truncate
      --context-length 40000
      --enable-torch-compile
      --max-running-requests 16
      --chat-template /llm_models/qwen3-32b/qwen3-template-nothink.jinja
    restart: unless-stopped
    volumes:
     - /home/user/scripts/models:/llm_models
    environment:
     - TORCHINDUCTOR_CACHE_DIR=/llm_models/inductor_root_cache_qwen3
    ports:
      - 8848:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]
```
